CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(255) NOT NULL
);

CREATE TABLE task (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    latitude    DOUBLE PRECISION NOT NULL,
    longitude   DOUBLE PRECISION NOT NULL,
    radius      INTEGER NOT NULL,
    is_complete BOOLEAN NOT NULL DEFAULT FALSE,
    due_date    DATE NOT NULL,
    owner_id    BIGINT NOT NULL REFERENCES app_user(id)
);

CREATE INDEX idx_task_owner ON task(owner_id);
CREATE INDEX idx_task_owner_due_date ON task(owner_id, due_date);